databases:
  - ams_test

access:
  ams_test:
    user: root
    pass:
    host: localhost
    port: 3306

tables:
  include:
    - all
  exclude:
#   - table_name

plugin_paths:
  - AnalyzeMySQL/plugins/col_size_fits_content

settings:
  col_size_fits_content:
    scan: [smallint, int, bigint, varchar, char, text] # do not include tinyint, it leads to too many false positives
    mangle: 50 # start to cry when the field size is more than 50% bigger than the biggest value

  join_match_col_definition:
    strategy: match_colname # alternatively you can use "foreign_key"

# Add your own plugins here
